language: python
sudo: false
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
env:
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=3.1
  - DJANGO=master
matrix:
  exclude:
    - { python: 3.5, env: DJANGO=3.0 }
    - { python: 3.5, env: DJANGO=3.1 }
    - { python: 3.5, env: DJANGO=master }
  include:
    - { python: 3.9, env: TOXENV=linters }
install:
  - pip install tox-travis coveralls

script:
  - tox

after_script:
  - coveralls
