language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=master
matrix:
  include:
    - { python: 3.6, env: TOXENV=flake }

install:
  - pip install tox-travis coveralls

script:
  - tox

after_script:
  - coveralls
